SELECT         TB_PRODUTO.DESCRICAO, TB_COR.COR,TB_PRODUTO.ID_PRODUTO
FROM            TB_COR INNER JOIN
                         TBL_PRODUTO_COR ON TB_COR.ID_COR = TBL_PRODUTO_COR.ID_COR INNER JOIN
                         TB_PRODUTO ON TBL_PRODUTO_COR.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
	ORDER BY DESCRICAO , COR