/*
	LISTAR OS PRODUTOS E TODAS AS CORES QUE ELES POSSUEM
	DADOS :
	ID_PRODUTO,DESCRICAO,COR ORDENAR POR DESCRICAO,COR
*/
SELECT 
PR.ID_PRODUTO 
,DESCRICAO
,COUNT(COR ) AS TOTAL_COR
FROM TB_PRODUTO AS PR JOIN TBL_PRODUTO_COR AS PC 
	ON PR.ID_PRODUTO = PC.ID_PRODUTO 
	JOIN TB_COR AS CR ON CR.ID_COR = PC.ID_COR 
GROUP BY PR.ID_PRODUTO ,DESCRICAO
ORDER BY DESCRICAO,COR

