/*
 NA VOLTA, NÃO ESQUECER DE MARCAR TODO O SCRIPT 
*/
SELECT        ID_EMPREGADO AS Código, DATA_NASCIMENTO, NOME, DATA_ADMISSAO, SALARIO
FROM            TB_EMPREGADO
WHERE        (SALARIO >= 3500)