SELECT TOP 3 * FROM TBL_COMISSAO
SELECT ID_EMPREGADO,COMISSAO FROM TB_EMPREGADO

UPDATE TBL_COMISSAO
SET PERC_COMISSAO = (SELECT COMISSAO FROM TB_EMPREGADO
					WHERE ID_EMPREGADO = TBL_COMISSAO.ID_EMPREGADO)