/*
	NESTE MOMENTO, COM USO DA TABELA JA MONTADA ( EMP_TEMP ) 
	FAZEMOS A MESCLAGEM.
*/

SET IDENTITY_INSERT EMP_TEMP ON
MERGE EMP_TEMP AS ET -- Tabela alvo
	USING TB_EMPREGADO AS E -- Tabela fonte
	ON ET.ID_EMPREGADO = E.ID_EMPREGADO -- Condição de comparação
		WHEN MATCHED AND E.SALARIO <> ET.SALARIO THEN
			UPDATE SET ET.SALARIO = E.SALARIO
		WHEN NOT MATCHED THEN
		INSERT (ID_EMPREGADO,NOME,ID_DEPARTAMENTO,ID_CARGO,DATA_ADMISSAO,
				DATA_NASCIMENTO,SALARIO, NUM_DEPEND, SINDICALIZADO, OBS, FOTO)
		VALUES (ID_EMPREGADO,NOME,ID_DEPARTAMENTO,ID_CARGO,DATA_ADMISSAO,
				DATA_NASCIMENTO,SALARIO, NUM_DEPEND, SINDICALIZADO, OBS, FOTO);
SET IDENTITY_INSERT EMP_TEMP OFF;