/*
	REFAZER O INSERT DA CONTAS_PAGAR USANDO CTE
	(COMMON TABLE EXPRESSION )
	PASSO 1 - DETERMINA DE FORMA SIMPLES QUAIS COLUNAS 
	REPRESENTAM A SUA TABELA (CURSOR)
	PASSO 2 - USO DO INSERT
	PASSO 3 - LISTAR CONTEUDO
*/
-- TRUNCATE ( LIMPEZA DA TABELA CONTAS_PAGAR )
TRUNCATE TABLE TBL_CONTAS_PAGAR  -- LIMPEZA
GO
-- CTE   -- POPULAÇÃO
WITH TB_DOC (DOCUMENTO,EMISSAO,LANCAMENTO,VENCIMENTO
				,VALOR_DOCUMENTO,VALOR_JUROS,VALOR_DESCONTO)
AS
(SELECT 
	CONCAT('COM-',FORMAT(ID_COMISSAO,'0000') ) AS DOCUMENTO
	,CONCAT(ANO_REF,FORMAT(MES_REF,'00'),'01') AS EMISSAO
	,GETDATE()
	,CONCAT(ANO_REF,FORMAT(MES_REF,'00'),'25') AS VENCIMENTO
	,BASE_COMISSAO*PERC_COMISSAO /100
	,0 ,0
FROM TBL_COMISSAO)
INSERT INTO TBL_CONTAS_PAGAR (DOCUMENTO,DATA_EMISSAO ,DATA_LANCTO 
								,DATA_VENCIMENTO,VALOR_DOCUMENTO
								,VALOR_JUROS,VALOR_DESCONTO )
SELECT * FROM TB_DOC;
SELECT * FROM TBL_CONTAS_PAGAR; --LISTANDO O CONTEUDO
