SELECT  dbo.TB_CARGO.ID_CARGO
		, dbo.TB_EMPREGADO.ID_CARGO AS CARGO_EMP
		, dbo.TB_CARGO.CARGO
		, dbo.TB_EMPREGADO.ID_EMPREGADO
		, dbo.TB_EMPREGADO.NOME
		, dbo.TB_EMPREGADO.DATA_NASCIMENTO
		, dbo.TB_EMPREGADO.DATA_ADMISSAO
FROM  dbo.TB_CARGO INNER JOIN dbo.TB_EMPREGADO
      ON dbo.TB_CARGO.ID_CARGO = dbo.TB_EMPREGADO.ID_CARGO