-- TRAZ AS 100 PRIMEIRAS LINHAS DE TB_PEDIDO
SELECT TOP 100 * FROM TB_PEDIDO
-- RESTRINGIR AS COLUNAS E LIBERAR TODAS AS LINHAS
SELECT ID_PEDIDO,DATA_EMISSAO,VLR_TOTAL ,STATUS
FROM TB_PEDIDO
-- DISTINÇÃO DO STATUS
SELECT DISTINCT STATUS FROM TB_PEDIDO