/*
	SELECT COM WITH ROLLUP E CUBE
*/
SELECT 
ID_EMPREGADO,MONTH(DATA_EMISSAO) AS MES_REF
,YEAR(DATA_EMISSAO) AS ANO_REF
,SUM(VLR_TOTAL) AS VALOR_FATURADO
FROM TB_PEDIDO
WHERE STATUS IN ('E','C')
GROUP BY ID_EMPREGADO,MONTH(DATA_EMISSAO),YEAR(DATA_EMISSAO)
--WITH ROLLUP
ORDER BY ID_EMPREGADO,ANO_REF ,MES_REF 

SELECT 
ID_EMPREGADO,MONTH(DATA_EMISSAO) AS MES_REF
,YEAR(DATA_EMISSAO) AS ANO_REF
,SUM(VLR_TOTAL) AS VALOR_FATURADO
FROM TB_PEDIDO
WHERE STATUS IN ('E','C')
GROUP BY ID_EMPREGADO,MONTH(DATA_EMISSAO),YEAR(DATA_EMISSAO)
WITH CUBE 
ORDER BY ID_EMPREGADO,ANO_REF ,MES_REF 