/* TRATAMENTO DE NULOS  */
SELECT ID_EMPREGADO, NOME, ISNULL(SALARIO,0) AS SALARIO, PREMIO_MENSAL,
ISNULL(SALARIO,0) + ISNULL(PREMIO_MENSAL,0) AS RENDA_TOTAL
FROM TB_EMPREGADO WHERE ID_EMPREGADO = 44

SELECT ID_EMPREGADO, NOME, SALARIO , PREMIO_MENSAL,
SALARIO + PREMIO_MENSAL AS RENDA_TOTAL
FROM TB_EMPREGADO --WHERE ID_EMPREGADO = 44

SELECT ID_EMPREGADO,SALARIO, PREMIO_MENSAL
,NULLIF(SALARIO,550) AS VOLTA_NULO  -- SE FOREM IGUAIS, VOLTA NULO
,NULLIF(SALARIO,PREMIO_MENSAL) AS VOLTA_VALOR
FROM TB_EMPREGADO WHERE ID_EMPREGADO = 21