/*
	ATUALIZAR A TABELA TBL_CONTAS_PAGAR E INSERIR:
	ZERO PARA JUROS E DESCONTO
	E USAR NEXT VALUE FOR SEQ_CONTAS_PAGAR PARA O CAMPO SEQUENCIA

*/
UPDATE DBO.TBL_CONTAS_PAGAR
SET VALOR_JUROS = 0,
   VALOR_DESCONTO = 0,
   SEQUENCIA = NEXT VALUE FOR SEQ_CONTAS_PAGAR

SELECT * FROM TBL_CONTAS_PAGAR 
WHERE DOCUMENTO >='COM-2305'
ORDER BY DOCUMENTO DESC