/*
	GRUPOS DE COMANDO :
		DDL - DATA DEFINITION LANGUAGE -> OBJETOS DO BANCO
		CREATE | ALTER | DROP 
		CRIAR | ALTERAR | DESMONTAR

		DML - DATA MANIPULATION LANGUAGE -> INFORMAÇÕES
		SELECT | INSERT | DELETE | TRUNCATE | UPDATE
		SELECIONAR | INSERIR | EXCLUIR | TRUNCAR | ATUALIZAR
*/