--AJUSTE DA TABELA COMISSAÕ PARA AQUELES CUJO VALOR ESTAVAM ERRADO
-- NÃO EXECUTAR LINHA ABAIXO
--SELECT * INTO COPIA_TBL_COMISSAO FROM TBL_COMISSAO 
DELETE FROM TBL_COMISSAO
INSERT INTO TBL_COMISSAO 
(ID_EMPREGADO, MES_REF,ANO_REF,VALOR_CANCELADO ,VALOR_FATURADO )
SELECT ID_EMPREGADO,MES_REF,ANO_REF,VALOR_CANCELADO,VALOR_FATURADO
FROM COPIA_TBL_COMISSAO WHERE ID_COMISSAO <385