--SELECT * FROM TBL_PRODUTO_COR
--INSERT COM OUTPUT
/*
	TABELA VIRTUAL CHAMADA inserted ( existe pelo uso do log )
*/
INSERT INTO TBL_PRODUTO_COR 
(ID_PRODUTO ,ID_COR ) OUTPUT inserted.*
SELECT DISTINCT ID_PRODUTO,ID_COR FROM TB_ITENSPEDIDO 