SELECT        COD_PARTICIPANTE, NOME, EMAIL
FROM            dbo.TBL_PARTICIPANTE
ORDER BY NOME

-- EXCLUIR LINHAS COM NOME EM BRANCO OU NULO
DELETE FROM DBO.TBL_PARTICIPANTE 
	WHERE NOME ='ELON MUSK' AND  COD_PARTICIPANTE <> 29