/*
	ESTRUTURA DA TABELA DE COMISSAO
	DICIONARIZAÇÃO
	FLUXO DE COMISSIONAMENTO
	VENDAS -> APURAÇÃO ->  GERAÇÃO DO MOVIMENTO
	N PEDIDOS -> SOMATORIO -> COMISSÃO
	IDENTIFICAR VENDEDOR
	IDENTIFICAR MES E ANO 
	IDENTIFICAR VALOR FATURADO
	VALOR_CANCELADO ( PEDIDOS DEVOLVIDOS PELOS CLIENTES )
	PERCENTUAL COMISSAO ( MANTER O PERCENTUAL USADO NA EPOCA)
	CHAVE DE ACESSO ( PRIMARY KEY )
	COLUNA			TIPO DE DADO		OBSERVAÇÃO
	ID_COMISSAO		INT AUTONUMERADO	CONTROLE PRINCIPAL
	ID_EMPREGADO	INT					FK - EMPREGADO
	MES_REF			TINYINT				MES FATURADO (1-12)
	ANO_REF			SMALLINT			32768 DE MAXIMO
	VALOR_FATURADO	DECIMAL(12,4)		PADRAO ZERO
	VALOR_CANCELADO	DECIMAL(12,4)		PADRAO ZERO
	PERC_COMISSAO	DECIMAL(6,3)		

*/