/*
	APLICAR O MERGE NA TABELA TBL_CONTAS_PAGAR ( ALVO )
	USANDO A TABELA TBL_PAGAMENTOS
	ATUALIZAR OS CAMPOS :
		DATA DE PAGAMENTO
		VALOR JUROS
		VALOR DESCONTO
*/
-- ADICIONAR 1 TAXA BANCARIA
--INSERT INTO TBL_PAGAMENTOS (DOCUMENTO,VALOR_PAGO ,DATA_PAGAMENTO )
--VALUES ('TX_BANC',110.00,GETDATE());
-- CONDIÇÕES DE USO:
-- TABELA DE PAGAMENTOS NÃO PODE ESTAR DUPLICADA.
-- TESTE : SELECT * FROM TBL_PAGAMENTOS ORDER BY DOCUMENTO
-- ESTRUTURA:
MERGE TBL_CONTAS_PAGAR PG
	USING TBL_PAGAMENTOS PAGTO
	ON PG.DOCUMENTO = PAGTO.DOCUMENTO
	WHEN MATCHED THEN
		UPDATE SET PG.DATA_PAGAMENTO = PAGTO.DATA_PAGAMENTO
		,PG.VALOR_JUROS = PAGTO.VALOR_JUROS
		,PG.VALOR_DESCONTO = PAGTO.VALOR_DESCONTO
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (DOCUMENTO,VALOR_DOCUMENTO,DATA_VENCIMENTO,DATA_PAGAMENTO)
		VALUES (DOCUMENTO,VALOR_PAGO,GETDATE(),DATA_PAGAMENTO);
SELECT * FROM TBL_CONTAS_PAGAR WHERE DATA_PAGAMENTO IS NOT NULL