-- AJUSTAR A BASE DE DADOS
--A  CRIAR UMA COLUNA ID_COR TIPO INT NA TABELA DE PRODUTOS
--    ADICIONAR UMA COLUNA A TABELA TB_PRODUTO (***)
--DDL CREATE | ALTER | DROP

--ALTER TABLE TB_PRODUTO
--	ADD ID_COR INT 
ALTER TABLE TB_PRODUTO DROP COLUMN TB_COR
SELECT * FROM TB_PRODUTO
SELECT ID_PRODUTO,ID_COR,ID_PEDIDO FROM TB_ITENSPEDIDO ORDER BY ID_PEDIDO

-- B - > ATUALIZAR A TABELA DE PRODUTO USANDO TB_ITENSPEDIDO COMO REFERENCIA.
--1 - SUB CONSULA RELACIONADA
UPDATE TB_PRODUTO
SET ID_COR = (SELECT TOP 1 ID_COR FROM TB_ITENSPEDIDO 
				WHERE TB_ITENSPEDIDO.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO )

-- B - JOIN
UPDATE TB_PRODUTO 
	SET ID_COR = TB_ITENSPEDIDO.id_cor 
FROM TB_PRODUTO JOIN TB_ITENSPEDIDO
	ON TB_PRODUTO.ID_PRODUTO = TB_ITENSPEDIDO.ID_PRODUTO 

