/*
	PAG 152 - 3 
		PRODUTOS QUE NUNCA FORAM VENDIDOS  - SUB CONSULTA

*/
SELECT *
FROM TB_PRODUTO
WHERE ID_PRODUTO NOT IN(SELECT ID_PRODUTO FROM TB_ITENSPEDIDO)
ORDER BY ID_PRODUTO

SELECT TB_PRODUTO.ID_PRODUTO
	,DESCRICAO
	,ITEM
FROM TB_PRODUTO LEFT JOIN TB_ITENSPEDIDO 
	ON TB_PRODUTO.ID_PRODUTO = TB_ITENSPEDIDO .ID_PRODUTO 
WHERE ITEM IS NULL
ORDER BY ID_PRODUTO