/*
	SEQUENCIA É LIVRE DA TABELA , SENDO USADA EM QQ COMANDO COMO SELECT POR EXEMPLO
	USO : COMO POR EXEMPLO NUMERO DE PROTOCOLO
	SE FOR USADO EM PK, MELHOR SER UMA SEQUENCIA EXCLUSIVA DA TABELA
*/
CREATE SEQUENCE SEQ_CONTAS_PAGAR 
START WITH 1
INCREMENT BY 1 
MINVALUE  1
MAXVALUE  100000
CYCLE CACHE  10