/*
	GRUPOS DE COMANDOS
		DDL  - DATA DEFINITION LANGUAGE OBJETOS
			CREATE	ALTER	DROP	
			CRIAR	ALTERAR	DESMONTAR
		
		DML	 - DATA MANIPULATION LANGUAGE INFORMAÇÕES
			SELECT		UPDATE		INSERT	DELETE
			SELECIONAR	ATUALIZAR	INSERIR	EXCLUIR
*/
CREATE TABLE TBL_PARTICIPANTE
(
	NOME	VARCHAR(80)
	,EMAIL	VARCHAR(100)
)
