-- FASE 1 
	SELECT * FROM NO1032.TB_PARTICIPANTES$
-- FASE 2 
	-- LIMPAR A TABELA TBL_PARTICIPANTE
	TRUNCATE TABLE DBO.TBL_PARTICIPANTE
	SELECT * FROM TBL_PARTICIPANTE 
-- FASE 3 - TRANSFERIR DADOS 
--	DE TB_PARTICIPANTES$ -> TBL_PARTICIPANTE
INSERT INTO DBO.TBL_PARTICIPANTE 
(NOME,EMAIL)
SELECT DISTINCT NOME,EMAIL 
FROM DBO.TB_PARTICIPANTES$ 
--FASE 4
-- DESMONTAR A TABELA TB_PARTICIPANTES$
DROP TABLE NO1032.TB_PARTICIPANTES$ 