/*
	FASE 1 - CRIAÇÃO 
	FASE 2 - POPULAR A TABELA
	TBL_CONTAS_PAGAR.
	DOCUMENTO			IDENTIFICADOR DO PAGAMENTO - PK
	DATA_EMISSAO		DATETIME
	DATA_LANCTO			DATETIME	DEFAULT GETDATE()
	DATA_VENCIMENTO		DATETIME
	DATA_PAGAMENTO		DATETIME
	VALOR_DOCUMENTO		TIPO_VALOR
	VALOR_JUROS			TIPO_VALOR
	VALOR_DESCONTO		TIPO_VALOR

*/
CREATE TABLE TBL_CONTAS_PAGAR
(
	DOCUMENTO			VARCHAR(20)		PRIMARY KEY
	,DATA_EMISSAO		DATETIME
	,DATA_LANCTO		DATETIME	
	,DATA_VENCIMENTO	DATETIME
	,DATA_PAGAMENTO		DATETIME
	,VALOR_DOCUMENTO	TIPO_VALOR
	,VALOR_JUROS		TIPO_VALOR
	,VALOR_DESCONTO		TIPO_VALOR
)