INSERT INTO TBL_COMISSAO
(ID_EMPREGADO,MES_REF,ANO_REF ,VALOR_FATURADO )
SELECT 
ID_EMPREGADO,MONTH(DATA_EMISSAO) AS MES_REF
,YEAR(DATA_EMISSAO) AS ANO_REF
,SUM(VLR_TOTAL) AS VALOR_FATURADO
FROM TB_PEDIDO
WHERE STATUS IN ('E','C')
GROUP BY ID_EMPREGADO,MONTH(DATA_EMISSAO),YEAR(DATA_EMISSAO)
ORDER BY ID_EMPREGADO,ANO_REF ,MES_REF