/*
	AJUSTE DA ANOMALIA DA TABELA EMPREGADO SELF JOIN
	-- COD_SUPERVISOR = 0
*/
ALTER TABLE TB_EMPREGADO
	ADD CONSTRAINT FK_EMP_SUP_PNO10 FOREIGN KEY (COD_SUPERVISOR)
		REFERENCES TB_EMPREGADO (ID_EMPREGADO)

-- CONSISTIR ATRAVES DE SUB SELECT

SELECT COD_SUPERVISOR
	FROM TB_EMPREGADO
	WHERE COD_SUPERVISOR IS NOT NULL
	 AND COD_SUPERVISOR NOT IN(SELECT ID_EMPREGADO FROM TB_EMPREGADO)
-- ATUALIZAR USANDO SUB SELECT COMO FILTRO
UPDATE TB_EMPREGADO
	SET COD_SUPERVISOR = NULL
	WHERE COD_SUPERVISOR IS NOT NULL
	 AND COD_SUPERVISOR NOT IN(SELECT ID_EMPREGADO FROM TB_EMPREGADO)
