/*
	UPDATE COM USO DE FROM E WHERE
*/

UPDATE TB_ITENSPEDIDO
SET ID_COR = NO1033.TBL_ITENS.id_cor 
FROM NO1033.TBL_ITENS 
WHERE TB_ITENSPEDIDO.ID_PEDIDO = NO1033.TBL_ITENS.ID_PEDIDO
AND TB_ITENSPEDIDO.ITEM = NO1033.TBL_ITENS.ITEM
AND TB_ITENSPEDIDO.ID_PRODUTO = NO1033.TBL_ITENS.ID_PRODUTO