/*
	exercicio:
		listar os seguintes dados da tabela de pedidos:
			id_empregado
			mes ( month(data_emissao)) 
			ano ( year(data_emissao))
			sum (vlr_total ) valor faturado
		filtro status = 'c'
		group by 
*/
SELECT ID_EMPREGADO,MONTH(DATA_EMISSAO) AS MES
,YEAR(DATA_EMISSAO) AS ANO
,SUM(VLR_TOTAL) AS VALOR_CANCELADO
INTO #TEMP_CANCELADO
FROM TB_PEDIDO WHERE STATUS ='C'
GROUP BY ID_EMPREGADO,MONTH(DATA_EMISSAO),YEAR(DATA_EMISSAO)
-- USO DE TABELA TEMPORARIA
SELECT * FROM #TEMP_CANCELADO 
SELECT TOP 10 * FROM TBL_COMISSAO
-- CRIAR CHAVE PRIMARIA EM #TEMP_CANCELADO
	ALTER TABLE #TEMP_CANCELADO 
	ADD ID_CANCELADO INT IDENTITY NOT NULL
		 ,CONSTRAINT PK_CANCELADO_PN10 PRIMARY KEY(ID_CANCELADO)
-- UPDATE 
UPDATE TBL_COMISSAO 
	SET VALOR_CANCELADO = #TEMP_CANCELADO.VALOR_CANCELADO 
	FROM TBL_COMISSAO JOIN [#TEMP_CANCELADO]
	ON TBL_COMISSAO.ID_EMPREGADO = #TEMP_CANCELADO.ID_EMPREGADO 
	AND MES_REF = MES AND ANO_REF = ANO