/*
	LISTAGEM :
		APRESENTAR OS SEGUINTES DADOS:
			ID_PRODUTO | DESCRICAO | COR | SOMATORIO QUANTIDADE VENDIDA
			TOP 5 DO ANO DE 2018 SÃO  OS MAIS VENDIDOS 
			RANKING -> ORDER BY DESC X TOP
	TABELAS:
		ITENSPEDIDO | COR |  PRODUTO | PEDIDO ( ANO 2018 )
		INNER JOIN
*/
SELECT TOP 5
PR.ID_PRODUTO 
,DESCRICAO
,COR
,SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM TB_ITENSPEDIDO IT JOIN TB_PRODUTO PR ON IT.ID_PRODUTO = PR.ID_PRODUTO
	INNER JOIN TB_COR C ON C.ID_COR = IT.ID_COR 
	INNER JOIN TB_PEDIDO P ON P.ID_PEDIDO = IT.ID_PEDIDO 
WHERE YEAR(DATA_EMISSAO) = 2018
GROUP BY PR.ID_PRODUTO,DESCRICAO,COR
ORDER BY TOTAL_VENDIDO DESC

SELECT SUM(QUANTIDADE) FROM TB_ITENSPEDIDO 
WHERE ID_PRODUTO = 22 
AND ID_COR = 16
AND ID_PEDIDO IN(SELECT ID_PEDIDO FROM TB_PEDIDO WHERE YEAR(DATA_EMISSAO) =2018)

SELECT * FROM TB_COR