/*
	EXERCICIO:
		PROJETAR 5% NA COLUNA PRECO_VENDA DA TABELA TB_PRODUTO
	EXIBIR: ID_PRODUTO,DESCRICAO,PRECO_VENDA,PROJECAO
*/
SELECT 
ID_PRODUTO
,DESCRICAO
,PRECO_VENDA 
,PRECO_VENDA*1.05 AS PROJECAO_UNITARIA
,QTD_REAL *(PRECO_VENDA*1.05) AS PROJECAO_ESTOQUE
,'1,05 ->INDICE APLICADO' AS OBS
FROM TB_PRODUTO
-- ADICIONAR A FONTE DE DADOS ( FROM ) A TABELA TB_TIPOPRODUTO
SELECT 
ID_PRODUTO
,TIPO
,DESCRICAO
,PRECO_VENDA 
,PRECO_VENDA*1.05 AS PROJECAO_UNITARIA
,QTD_REAL *(PRECO_VENDA*1.05) AS PROJECAO_ESTOQUE
,'1,05 ->INDICE APLICADO' AS OBS
FROM TB_PRODUTO INNER JOIN TB_TIPOPRODUTO 
ON TB_PRODUTO.id_tipo = TB_TIPOPRODUTO.ID_TIPO
ORDER BY TIPO,DESCRICAO