/*
	EXERCICIO :
		LISTAGEM COM A SEGUINTE FORMATAÇÃO:
		NOME EMP,ID_EMP,SOMA(MES1) ,SOMA(MES2),SOMA(MES3)
		FILTRO : ANO DE 2016 E PRIMEIRO TRIMESTRE
		TABELAS : EMPREGADO X TB_PEDIDO
*/
-- SUB CONSULTA
SELECT 
NOME
,ID_EMPREGADO
,(SELECT SUM(VLR_TOTAL)  FROM TB_PEDIDO WHERE YEAR(DATA_EMISSAO)=2016
	AND MONTH(DATA_EMISSAO)=1 AND ID_EMPREGADO = TB_EMPREGADO.ID_EMPREGADO ) AS M_01 
,(SELECT SUM(VLR_TOTAL) FROM TB_PEDIDO WHERE YEAR(DATA_EMISSAO)=2016
	AND MONTH(DATA_EMISSAO)=2 AND ID_EMPREGADO = TB_EMPREGADO.ID_EMPREGADO ) AS M_02 
,(SELECT SUM(VLR_TOTAL) FROM TB_PEDIDO WHERE YEAR(DATA_EMISSAO)=2016
	AND MONTH(DATA_EMISSAO)=3 AND ID_EMPREGADO = TB_EMPREGADO.ID_EMPREGADO ) AS M_03 

FROM TB_EMPREGADO
WHERE ID_EMPREGADO IN(SELECT ID_EMPREGADO FROM TB_PEDIDO)