/*
		JOIN ( ASSOCIAÇÃO ENTRE TABELAS ) 
		INNER  - INERENTE - DENTRO ( INTRINSICO ) -> INTERSEÇÃO
		OUTER  - OUTROS (*)
			LEFT	- A ESQUERDA ( TABELA LOGO APOS O FROM )
			RIGHT	- A DIREITA	
			FULL	- COMPLETA (CONTEMPLA TODAS AS POSSIBILIDADES)
		CROSS		- ALEATORIA
	(*)  LEFT | RIGHT | FULL  (SEMPRE ORIENTADO EM FUNÇÃO DO FROM)

*/
