CREATE TABLE TBL_COMISSAO
(
	ID_COMISSAO		INT	IDENTITY	PRIMARY KEY,
	ID_EMPREGADO	INT	FOREIGN KEY REFERENCES 
						TB_EMPREGADO (ID_EMPREGADO),
	MES_REF			TINYINT,
	ANO_REF			SMALLINT,
	VALOR_FATURADO	DECIMAL(14,4)	DEFAULT 0,
	VALOR_CANCELADO	DECIMAL(14,4)	DEFAULT 0,
	PERC_COMISSAO	DECIMAL(6,3)	DEFAULT 0

)