/*
		MODULO DE COMISSÃO
		FUNÇÃO : APURAR O VALOR DE COMISSÃO PARA CADA VENDEDOR
		DADOS DA COMISSÃO
		OBEDECEM 3 PREMISSAS:
			1 - QUEM FEZ OU VENDEU ( EMPREGADO-> ID_EMPREGADO )
			2 - QUANDO FEZ ( EMITIDO  O PEDIDO ) 
			3 - QUANTO FATUROU ( SOMA DOS VALORES FATURADOS )
		FONTE DA INFORMAÇÃO : TB_PEDIDO EXCETO PENDENTES

*/
SELECT 
ID_EMPREGADO,MONTH(DATA_EMISSAO) AS MES_REF
,YEAR(DATA_EMISSAO) AS ANO_REF
,SUM(VLR_TOTAL) AS VALOR_FATURADO
FROM TB_PEDIDO
WHERE STATUS <> 'P'
GROUP BY ID_EMPREGADO,MONTH(DATA_EMISSAO),YEAR(DATA_EMISSAO)