-- USO DA SUB CONSULTA COMO COLUNA
-- EMPREGADO X PEDIDOS
SELECT
ID_EMPREGADO
,NOME
,FORMAT(DATA_ADMISSAO,'dd/MM/yyyy') AS DATA_ADMISSAO
,(SELECT ISNULL(SUM(VLR_TOTAL),0) FROM TB_PEDIDO 
		WHERE STATUS = 'E' AND YEAR(DATA_EMISSAO) = 2016
		AND ID_EMPREGADO = TB_EMPREGADO.ID_EMPREGADO ) AS VENDAS
FROM TB_EMPREGADO
WHERE ID_EMPREGADO  IN(SELECT ID_EMPREGADO FROM TB_PEDIDO)
-- JOIN COM GROUP BY
SELECT 
TB_EMPREGADO.ID_EMPREGADO
,NOME 
,FORMAT(DATA_ADMISSAO,'dd/MM/yyyy') AS DATA_ADMISSAO
,SUM(VLR_TOTAL) AS VENDAS 
FROM TB_EMPREGADO INNER JOIN TB_PEDIDO
ON TB_PEDIDO.ID_EMPREGADO = TB_EMPREGADO.ID_EMPREGADO
WHERE STATUS = 'E' AND YEAR(DATA_EMISSAO) = 2016
GROUP BY TB_EMPREGADO.ID_EMPREGADO,NOME ,FORMAT(DATA_ADMISSAO,'dd/MM/yyyy')