SELECT        E.ID_EMPREGADO, E.DATA_ADMISSAO, E.SALARIO, C.ID_CARGO, C.CARGO
FROM            TB_EMPREGADO AS E RIGHT OUTER JOIN
                         TB_CARGO AS C ON E.ID_CARGO = C.ID_CARGO
	ORDER BY ID_EMPREGADO 

SELECT        E.ID_EMPREGADO, E.DATA_ADMISSAO, E.SALARIO, C.ID_CARGO, C.CARGO
FROM            TB_EMPREGADO AS E LEFT OUTER JOIN
                         TB_CARGO AS C ON E.ID_CARGO = C.ID_CARGO
	ORDER BY ID_CARGO 

SELECT        E.ID_EMPREGADO, E.DATA_ADMISSAO, E.SALARIO, C.ID_CARGO, C.CARGO
FROM            TB_EMPREGADO AS E INNER JOIN
                         TB_CARGO AS C ON E.ID_CARGO = C.ID_CARGO
	ORDER BY ID_EMPREGADO 

SELECT        E.ID_EMPREGADO, E.DATA_ADMISSAO, E.SALARIO, C.ID_CARGO, C.CARGO
FROM            TB_EMPREGADO AS E FULL JOIN
                         TB_CARGO AS C ON E.ID_CARGO = C.ID_CARGO
	ORDER BY ID_EMPREGADO 

	SELECT        E.ID_EMPREGADO, E.DATA_ADMISSAO, E.SALARIO, C.ID_CARGO, C.CARGO
FROM            TB_EMPREGADO AS E CROSS JOIN
                         TB_CARGO AS C 
	ORDER BY ID_EMPREGADO 
