-- CLAUSULA OUTPUT
/*
	USA O SETOR DE LOG DO BANCO... ( ARQUIVO LDF)
	USA 2 TABELAS VIRTUAIS (deleted, inserted)
	COMANDOS: INSERT | UPDATE | DELETE 
	EXERCITAR USANDO TRANSAÇÃO EXPLICITA 
	- CONTROLE MAIOR SOBRE A TRANSAÇÃO
		INICIAR TRANSAÇÃO ( BEGIN TRAN )
			TESTE SE HA ERRO
				SE SIM, APLICAR ( ROLLBACK TRAN ) VOLTAR ATRÁS ->DESFAZER
				SE NÃO, APLICAR ( COMMIT TRAN ) - COMPROMETER -> CONFIRMAR
*/
BEGIN TRANSACTION
	INSERT INTO TB_CARGO (CARGO,SALARIO_INIC )
		OUTPUT inserted.* 
		VALUES ('ATENDENTE',-1800.00)
	IF @@ERROR > 0
		BEGIN
			ROLLBACK TRAN
			PRINT 'EFETOU ROLLBACK'
		END
	ELSE
		BEGIN
			COMMIT TRAN
			PRINT 'EFETOU COMMIT'
		END