/*
	ALTER TABLE -> ADICIONAR UMA CONSTRAINT ( RESTRIÇÃO ) DE 
	CHECAGEM
	 1- ATRAVES DE VISUAL
	 2- ATRAVES DE SCRIPT T-SQL.
*/
	ALTER TABLE TBL_COMISSAO
		ADD CONSTRAINT CHECA_CANCELADO_PNO10 CHECK(VALOR_CANCELADO>=0);
	ALTER TABLE TBL_COMISSAO
		ADD CONSTRAINT CHECA_PERC_COMISSAO_PNO10
			CHECK(PERC_COMISSAO>=0)