/*
	FICHA DO CLIENTE
*/
SELECT 
	TOTAL_COMPRADO 
	,ANO
	,TB_CLIENTE.ID_CLIENTE
	,NOME
FROM
(
	SELECT ID_CLIENTE
			,SUM(VLR_TOTAL) AS TOTAL_COMPRADO
			,YEAR(DATA_EMISSAO) ANO
		FROM TB_PEDIDO WHERE STATUS = 'E'
		GROUP BY ID_CLIENTE,YEAR(DATA_EMISSAO)
) AS FICHA_CLIENTE JOIN TB_CLIENTE
	ON FICHA_CLIENTE .ID_CLIENTE = TB_CLIENTE.ID_CLIENTE 
ORDER BY TOTAL_COMPRADO DESC,ANO 