/*
2. Liste a tabela TB_PRODUTO, mostrando as colunas ID_PRODUTO
, DESCRICAO,PRECO_CUSTO e PRECO_VENDA e calculando o lucro unitário 
(PRECO_VENDA – PRECO_CUSTO);

3. Liste a tabela TB_PRODUTO, mostrando 
os campos ID_PRODUTO e DESCRICAO e
calculando o valor total investido no estoque daquele produto 
(QTD_REAL * PRECO_CUSTO);

4. Liste a tabela TB_ITENSPEDIDO, mostrando 
as colunas ID_PEDIDO, ITEM, ID_PRODUTO, PR_UNITARIO
, QUANTIDADE e DESCONTO e calculando o valor de cada
item (PR_UNITARIO * QUANTIDADE * (1-DESCONTO/100));
*/
SELECT ID_PRODUTO,DESCRICAO ,PRECO_CUSTO ,PRECO_VENDA 
,PRECO_VENDA -PRECO_CUSTO AS LUCRO
FROM TB_PRODUTO

SELECT ID_PRODUTO,DESCRICAO,QTD_REAL *PRECO_CUSTO AS ESTOQUE
FROM TB_PRODUTO

SELECT ID_PEDIDO,ITEM,ID_PRODUTO,PR_UNITARIO ,QUANTIDADE 
,DESCONTO ,(PR_UNITARIO*QUANTIDADE*(1-DESCONTO/100))
FROM TB_ITENSPEDIDO 