/*
	SUB CONSULTA COMO FROM
*/
SELECT FICHA_EMPREGADO .*
FROM
(SELECT TB_CARGO.CARGO 
	,TB_EMPREGADO.NOME
	,TB_EMPREGADO.DATA_NASCIMENTO 
	,TB_EMPREGADO.COD_SUPERVISOR 
	,TB_DEPARTAMENTO.DEPARTAMENTO 
	FROM TB_EMPREGADO JOIN TB_CARGO 
		ON TB_EMPREGADO.ID_CARGO = TB_CARGO.ID_CARGO 
		 JOIN TB_DEPARTAMENTO
		ON TB_EMPREGADO.ID_DEPARTAMENTO = TB_DEPARTAMENTO.ID_DEPARTAMENTO 
) AS FICHA_EMPREGADO